# Alternative compose file with architecture-specific image selection
# Usage: docker compose -f compose.arch-specific.yaml up

services:
  sqlserver:
    # This will use the image specified in the .env file based on your architecture
    image: ${SQL_IMAGE:-mcr.microsoft.com/azure-sql-edge:latest}
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_SA_PASSWORD:-YourStrong@Passw0rd}
      - MSSQL_PID=Developer
    ports:
      - "${SQL_PORT:-1433}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SQL_SA_PASSWORD:-YourStrong@Passw0rd} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlserver-data:
    driver: local

networks:
  app-network:
    driver: bridge
