#!/bin/bash
# Setup environment file for Accessible project
# All services use amd64 architecture (works via Rosetta 2 on Apple Silicon)

ARCH=$(uname -m)

echo "=== Accessible Environment Setup ==="
echo "Detected architecture: $ARCH"
echo ""

# We always use SQL Server 2022 (amd64) for consistency
SQL_IMAGE="mcr.microsoft.com/mssql/server:2022-latest"

if [ "$ARCH" = "arm64" ]; then
    echo "✓ Apple Silicon detected"
    echo "  All images use amd64 architecture (runs via Rosetta 2)"
elif [ "$ARCH" = "x86_64" ]; then
    echo "✓ Intel/AMD detected"
    echo "  All images use native amd64 architecture"
else
    echo "⚠ Unknown architecture: $ARCH"
    echo "  Proceeding with amd64 (may require Rosetta 2)"
fi

echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    read -p ".env file already exists. Overwrite? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Cancelled. Existing .env file preserved."
        exit 0
    fi
fi

# Create .env file from .env.example or template
if [ -f ".env.example" ]; then
    echo "Creating .env from .env.example..."
    cp .env.example .env
    echo "✓ .env file created"
else
    echo "Creating .env from template..."
    cat > .env << EOF
# SQL Server Configuration
# Auto-generated by setup-env.sh on $(date)

# Project version (from version.json)
VERSION=1.0.0

# SQL Server 2022 - Works on both Apple Silicon (via Rosetta 2) and Intel/AMD
SQL_IMAGE=$SQL_IMAGE

# Database password (must be strong: 8+ chars, uppercase, lowercase, numbers, symbols)
SQL_SA_PASSWORD=YourStrong@Passw0rd

# Port mapping
SQL_PORT=1433
EOF
    echo "✓ .env file created"
fi

echo ""
echo "⚠️  IMPORTANT: Change SQL_SA_PASSWORD in .env to a secure password!"
echo ""
echo "Next steps:"
echo "  1. Edit .env and update SQL_SA_PASSWORD"
echo "  2. Run: docker compose up -d"
echo "  3. Run: ./init-database.sh"
echo ""
