#!/bin/bash

# Detect architecture and set appropriate SQL Server image
ARCH=$(uname -m)

echo "Detected architecture: $ARCH"

if [ "$ARCH" = "arm64" ]; then
    echo "Setting up for Apple Silicon (ARM64)..."
    SQL_IMAGE="mcr.microsoft.com/azure-sql-edge:latest"
elif [ "$ARCH" = "x86_64" ]; then
    echo "Setting up for Intel/AMD (x86_64)..."
    # Check if Rosetta is enabled in Docker Desktop
    echo "You can use either:"
    echo "  1. Azure SQL Edge (native ARM emulation): mcr.microsoft.com/azure-sql-edge:latest"
    echo "  2. Full SQL Server (requires Rosetta): mcr.microsoft.com/mssql/server:2022-latest"
    echo ""
    read -p "Use full SQL Server instead of Azure SQL Edge? (y/N): " use_full
    if [[ $use_full =~ ^[Yy]$ ]]; then
        SQL_IMAGE="mcr.microsoft.com/mssql/server:2022-latest"
    else
        SQL_IMAGE="mcr.microsoft.com/azure-sql-edge:latest"
    fi
else
    echo "Unknown architecture: $ARCH"
    SQL_IMAGE="mcr.microsoft.com/azure-sql-edge:latest"
fi

# Create .env file
cat > .env << EOF
# SQL Server Configuration
# Auto-generated by setup-env.sh on $(date)

# Selected image for architecture: $ARCH
SQL_IMAGE=$SQL_IMAGE

# Database password (change this to something secure!)
SQL_SA_PASSWORD=YourStrong@Passw0rd

# Port mapping
SQL_PORT=1433
EOF

echo ""
echo "Created .env file with image: $SQL_IMAGE"
echo ""
echo "⚠️  IMPORTANT: Edit .env and change SQL_SA_PASSWORD to a secure password!"
echo ""
echo "To start SQL Server, run: docker compose up -d"
